//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.28 at 04:03:08 PM CEST 
//


package org.gleif.data.schema.rr._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeIDTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="NodeIDTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LEI"/&gt;
 *     &lt;enumeration value="ISO_17442_COMPATIBLE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NodeIDTypeEnum")
@XmlEnum
public enum NodeIDTypeEnum {


    /**
     * An LEI code taken from the LEI issuing prefix namespace of a
     *                         GLEIS LOU.
     * 
     */
    LEI,

    /**
     * An ISO 17442-compatible code, not taken from the LEI issuing
     *                         prefix namespace of a GLEIS LOU.
     * 
     */
    ISO_17442_COMPATIBLE;

    public String value() {
        return name();
    }

    public static NodeIDTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
