//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.28 at 04:03:08 PM CEST 
//


package org.gleif.data.schema.rr._2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NodeID" type="{http://www.gleif.org/data/schema/rr/2016}LEIType"/&gt;
 *         &lt;element name="NodeIDType" type="{http://www.gleif.org/data/schema/rr/2016}NodeIDTypeEnum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType", propOrder = {
    "nodeID",
    "nodeIDType"
})
public class NodeType {

    @XmlElement(name = "NodeID", required = true)
    protected String nodeID;
    @XmlElement(name = "NodeIDType", required = true)
    @XmlSchemaType(name = "string")
    protected NodeIDTypeEnum nodeIDType;

    /**
     * Gets the value of the nodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeID() {
        return nodeID;
    }

    /**
     * Sets the value of the nodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeID(String value) {
        this.nodeID = value;
    }

    /**
     * Gets the value of the nodeIDType property.
     * 
     * @return
     *     possible object is
     *     {@link NodeIDTypeEnum }
     *     
     */
    public NodeIDTypeEnum getNodeIDType() {
        return nodeIDType;
    }

    /**
     * Sets the value of the nodeIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeIDTypeEnum }
     *     
     */
    public void setNodeIDType(NodeIDTypeEnum value) {
        this.nodeIDType = value;
    }

}
