//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.28 at 04:03:08 PM CEST 
//


package org.gleif.data.schema.rr._2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationshipQualifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationshipQualifierType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="QualifierDimension" type="{http://www.gleif.org/data/schema/rr/2016}QualifierDimensionEnum"/&gt;
 *         &lt;element name="QualifierCategory" type="{http://www.gleif.org/data/schema/rr/2016}QualifierCategoryTypeEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationshipQualifierType", propOrder = {
    "qualifierDimension",
    "qualifierCategory"
})
public class RelationshipQualifierType {

    @XmlElement(name = "QualifierDimension", required = true)
    @XmlSchemaType(name = "string")
    protected QualifierDimensionEnum qualifierDimension;
    @XmlElement(name = "QualifierCategory")
    @XmlSchemaType(name = "string")
    protected QualifierCategoryTypeEnum qualifierCategory;

    /**
     * Gets the value of the qualifierDimension property.
     * 
     * @return
     *     possible object is
     *     {@link QualifierDimensionEnum }
     *     
     */
    public QualifierDimensionEnum getQualifierDimension() {
        return qualifierDimension;
    }

    /**
     * Sets the value of the qualifierDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifierDimensionEnum }
     *     
     */
    public void setQualifierDimension(QualifierDimensionEnum value) {
        this.qualifierDimension = value;
    }

    /**
     * Gets the value of the qualifierCategory property.
     * 
     * @return
     *     possible object is
     *     {@link QualifierCategoryTypeEnum }
     *     
     */
    public QualifierCategoryTypeEnum getQualifierCategory() {
        return qualifierCategory;
    }

    /**
     * Sets the value of the qualifierCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifierCategoryTypeEnum }
     *     
     */
    public void setQualifierCategory(QualifierCategoryTypeEnum value) {
        this.qualifierCategory = value;
    }

}
