//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALTERNATIVE_LANGUAGE_LEGAL_ADDRESS"/>
 *     &lt;enumeration value="ALTERNATIVE_LANGUAGE_HEADQUARTERS_ADDRESS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AddressTypeEnum")
@XmlEnum
public enum AddressTypeEnum {


    /**
     * Registered address of the entity in the legal jurisdiction, in an
     *             alternative language used in the legal jurisdiction.
     * 
     */
    ALTERNATIVE_LANGUAGE_LEGAL_ADDRESS,

    /**
     * Address of the headquarters of the entity, in an alternative language
     *             used in the legal jurisdiction.
     * 
     */
    ALTERNATIVE_LANGUAGE_HEADQUARTERS_ADDRESS;

    public String value() {
        return name();
    }

    public static AddressTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
