//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociatedEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AssociatedLEI" type="{http://www.gleif.org/data/schema/leidata/2016}LEIType"/>
 *         &lt;element name="AssociatedEntityName" type="{http://www.gleif.org/data/schema/leidata/2016}NameType"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" use="required" type="{http://www.gleif.org/data/schema/leidata/2016}AssociatedEntityTypeEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedEntityType", propOrder = {
    "associatedLEI",
    "associatedEntityName"
})
public class AssociatedEntityType {

    @XmlElement(name = "AssociatedLEI")
    protected String associatedLEI;
    @XmlElement(name = "AssociatedEntityName")
    protected NameType associatedEntityName;
    @XmlAttribute(name = "type", required = true)
    protected AssociatedEntityTypeEnum type;

    /**
     * Gets the value of the associatedLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedLEI() {
        return associatedLEI;
    }

    /**
     * Sets the value of the associatedLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedLEI(String value) {
        this.associatedLEI = value;
    }

    /**
     * Gets the value of the associatedEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getAssociatedEntityName() {
        return associatedEntityName;
    }

    /**
     * Sets the value of the associatedEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setAssociatedEntityName(NameType value) {
        this.associatedEntityName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedEntityTypeEnum }
     *     
     */
    public AssociatedEntityTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedEntityTypeEnum }
     *     
     */
    public void setType(AssociatedEntityTypeEnum value) {
        this.type = value;
    }

}
