//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssociatedEntityTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssociatedEntityTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FUND_FAMILY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssociatedEntityTypeEnum")
@XmlEnum
public enum AssociatedEntityTypeEnum {


    /**
     * The legal entity is a fund, and the associated entity is the manager of
     *             the fund. 
     * 
     */
    FUND_FAMILY;

    public String value() {
        return name();
    }

    public static AssociatedEntityTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
