//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.28 at 04:03:08 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EntityStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ACTIVE"/&gt;
 *     &lt;enumeration value="INACTIVE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EntityStatusEnum")
@XmlEnum
public enum EntityStatusEnum {


    /**
     * As of the last report or update, the legal entity reported that it was
     *             legally registered and operating. 
     * 
     */
    ACTIVE,

    /**
     * It has been determined that the entity that was assigned the LEI is no
     *             longer legally registered and/or operating, whether as a result of business closure,
     *             acquisition by or merger with another (or new) entity, or determination of illegitimacy. 
     * 
     */
    INACTIVE;

    public String value() {
        return name();
    }

    public static EntityStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
