//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.28 at 04:03:08 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityCategoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EntityCategoryTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="BRANCH"/&gt;
 *     &lt;enumeration value="FUND"/&gt;
 *     &lt;enumeration value="SOLE_PROPRIETOR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EntityCategoryTypeEnum")
@XmlEnum
public enum EntityCategoryTypeEnum {


    /**
     * The legal entity is a branch of another legal entity.
     * 
     */
    BRANCH,

    /**
     * The legal entity is a fund managed by another legal
     *             entity.
     * 
     */
    FUND,

    /**
     * The legal entity is an individual acting in a business
     *             capacity.
     * 
     */
    SOLE_PROPRIETOR;

    public String value() {
        return name();
    }

    public static EntityCategoryTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
