//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityCategoryTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityCategoryTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="BRANCH"/>
 *     &lt;enumeration value="FUND"/>
 *     &lt;enumeration value="SOLE_PROPRIETOR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityCategoryTypeEnum")
@XmlEnum
public enum EntityCategoryTypeEnum {


    /**
     * The legal entity is a branch of another legal entity.
     * 
     */
    BRANCH,

    /**
     * The legal entity is a fund managed by another legal
     *             entity.
     * 
     */
    FUND,

    /**
     * The legal entity is an individual acting in a business
     *             capacity.
     * 
     */
    SOLE_PROPRIETOR;

    public String value() {
        return name();
    }

    public static EntityCategoryTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
