//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LEIData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LEIData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LEIHeader" type="{http://www.gleif.org/data/schema/leidata/2016}LEIHeaderType"/>
 *         &lt;element name="LEIRecords" type="{http://www.gleif.org/data/schema/leidata/2016}LEIRecordsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LEIData", propOrder = {
    "leiHeader",
    "leiRecords"
})
public class LEIData {

    @XmlElement(name = "LEIHeader", required = true)
    protected LEIHeaderType leiHeader;
    @XmlElement(name = "LEIRecords", required = true)
    protected LEIRecordsType leiRecords;

    /**
     * Gets the value of the leiHeader property.
     * 
     * @return
     *     possible object is
     *     {@link LEIHeaderType }
     *     
     */
    public LEIHeaderType getLEIHeader() {
        return leiHeader;
    }

    /**
     * Sets the value of the leiHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEIHeaderType }
     *     
     */
    public void setLEIHeader(LEIHeaderType value) {
        this.leiHeader = value;
    }

    /**
     * Gets the value of the leiRecords property.
     * 
     * @return
     *     possible object is
     *     {@link LEIRecordsType }
     *     
     */
    public LEIRecordsType getLEIRecords() {
        return leiRecords;
    }

    /**
     * Sets the value of the leiRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEIRecordsType }
     *     
     */
    public void setLEIRecords(LEIRecordsType value) {
        this.leiRecords = value;
    }

}
