//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransliteratedOtherEntityNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransliteratedOtherEntityNameType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.gleif.org/data/schema/leidata/2016>TransliteratedNameType">
 *       &lt;attribute name="type" use="required" type="{http://www.gleif.org/data/schema/leidata/2016}TransliteratedEntityNameTypeEnum" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransliteratedOtherEntityNameType")
public class TransliteratedOtherEntityNameType
    extends TransliteratedNameType
{

    @XmlAttribute(name = "type", required = true)
    protected TransliteratedEntityNameTypeEnum type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TransliteratedEntityNameTypeEnum }
     *     
     */
    public TransliteratedEntityNameTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransliteratedEntityNameTypeEnum }
     *     
     */
    public void setType(TransliteratedEntityNameTypeEnum value) {
        this.type = value;
    }

}
