//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransliteratedOtherAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransliteratedOtherAddressType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gleif.org/data/schema/leidata/2016}TransliteratedAddressType">
 *       &lt;attribute name="type" use="required" type="{http://www.gleif.org/data/schema/leidata/2016}TransliteratedAddressTypeEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransliteratedOtherAddressType")
public class TransliteratedOtherAddressType
    extends TransliteratedAddressType
{

    @XmlAttribute(name = "type", required = true)
    protected TransliteratedAddressTypeEnum type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TransliteratedAddressTypeEnum }
     *     
     */
    public TransliteratedAddressTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransliteratedAddressTypeEnum }
     *     
     */
    public void setType(TransliteratedAddressTypeEnum value) {
        this.type = value;
    }

}
