//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransliteratedEntityNameTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransliteratedEntityNameTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="PREFERRED_ASCII_TRANSLITERATED_LEGAL_NAME"/>
 *     &lt;enumeration value="AUTO_ASCII_TRANSLITERATED_LEGAL_NAME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransliteratedEntityNameTypeEnum")
@XmlEnum
public enum TransliteratedEntityNameTypeEnum {


    /**
     * Legal name of the entity transliterated to ASCII characters, provided by
     *             the entity for this purpose.
     * 
     */
    PREFERRED_ASCII_TRANSLITERATED_LEGAL_NAME,

    /**
     * Legal name of the entity transliterated to ASCII characters,
     *             auto-transliterated by the managing LOU.
     * 
     */
    AUTO_ASCII_TRANSLITERATED_LEGAL_NAME;

    public String value() {
        return name();
    }

    public static TransliteratedEntityNameTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
