//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileContentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileContentEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LOU_FULL_PUBLISHED"/>
 *     &lt;enumeration value="LOU_DELTA_PUBLISHED"/>
 *     &lt;enumeration value="GLEIF_FULL_PUBLISHED"/>
 *     &lt;enumeration value="GLEIF_DELTA_PUBLISHED"/>
 *     &lt;enumeration value="QUERY_RESPONSE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FileContentEnum")
@XmlEnum
public enum FileContentEnum {


    /**
     * The file contains all LEI Data Records published by an LOU (all LEI Data
     *             Records for which the LOU is the 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;code xmlns:lei="http://www.gleif.org/data/schema/leidata/2016" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;ManagingLOU&lt;/code&gt;
     * </pre>
     * ) as of the date/time the file
     *             is created. 
     * 
     */
    LOU_FULL_PUBLISHED,

    /**
     * The file contains those LEI Data Records published by an LOU (all LEI
     *             Data Records for which the LOU is the 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;code xmlns:lei="http://www.gleif.org/data/schema/leidata/2016" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;ManagingLOU&lt;/code&gt;
     * </pre>
     * ) which are new or changed
     *             since the 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;code xmlns:lei="http://www.gleif.org/data/schema/leidata/2016" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;DeltaStart&lt;/code&gt;
     * </pre>
     *  date specified in the header, as of the date/time the
     *             file is created.
     * 
     */
    LOU_DELTA_PUBLISHED,

    /**
     * The file contains all LEI Data Records published by GLEIF (including all
     *             LEI Data Records from all LOUs) as of the date/time the file is created.
     *           
     * 
     */
    GLEIF_FULL_PUBLISHED,

    /**
     * The file contains those LEI Data Records published by GLEIF (including
     *             all LEI Data Records from all LOUs) which are new or changed since the
     *               
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;code xmlns:lei="http://www.gleif.org/data/schema/leidata/2016" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;DeltaStart&lt;/code&gt;
     * </pre>
     *  specified in the header, as of the date/time the file is
     *             created.
     * 
     */
    GLEIF_DELTA_PUBLISHED,

    /**
     * The file contains records matching criteria specified in a query.
     *           
     * 
     */
    QUERY_RESPONSE;

    public String value() {
        return name();
    }

    public static FileContentEnum fromValue(String v) {
        return valueOf(v);
    }

}
