//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalFormType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegalFormType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityLegalFormCode" type="{http://www.gleif.org/data/schema/leidata/2016}LegalFormEnum"/>
 *         &lt;element name="OtherLegalForm" type="{http://www.gleif.org/data/schema/leidata/2016}Tokenized500Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegalFormType", propOrder = {
    "entityLegalFormCode",
    "otherLegalForm"
})
public class LegalFormType {

    @XmlElement(name = "EntityLegalFormCode", required = true)
    protected String entityLegalFormCode;
    @XmlElement(name = "OtherLegalForm")
    protected String otherLegalForm;

    /**
     * Gets the value of the entityLegalFormCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityLegalFormCode() {
        return entityLegalFormCode;
    }

    /**
     * Sets the value of the entityLegalFormCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityLegalFormCode(String value) {
        this.entityLegalFormCode = value;
    }

    /**
     * Gets the value of the otherLegalForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLegalForm() {
        return otherLegalForm;
    }

    /**
     * Sets the value of the otherLegalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLegalForm(String value) {
        this.otherLegalForm = value;
    }

}
