//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuccessorEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuccessorEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SuccessorLEI" type="{http://www.gleif.org/data/schema/leidata/2016}LEIType"/>
 *         &lt;element name="SuccessorEntityName" type="{http://www.gleif.org/data/schema/leidata/2016}NameType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuccessorEntityType", propOrder = {
    "successorLEI",
    "successorEntityName"
})
public class SuccessorEntityType {

    @XmlElement(name = "SuccessorLEI")
    protected String successorLEI;
    @XmlElement(name = "SuccessorEntityName")
    protected NameType successorEntityName;

    /**
     * Gets the value of the successorLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccessorLEI() {
        return successorLEI;
    }

    /**
     * Sets the value of the successorLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccessorLEI(String value) {
        this.successorLEI = value;
    }

    /**
     * Gets the value of the successorEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getSuccessorEntityName() {
        return successorEntityName;
    }

    /**
     * Sets the value of the successorEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setSuccessorEntityName(NameType value) {
        this.successorEntityName = value;
    }

}
