//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 11:47:31 PM CEST 
//


package org.gleif.data.schema.leidata._2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidationAuthorityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidationAuthorityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidationAuthorityID" type="{http://www.gleif.org/data/schema/leidata/2016}RegistrationAuthorityEnum"/>
 *         &lt;element name="OtherValidationAuthorityID" type="{http://www.gleif.org/data/schema/leidata/2016}Tokenized500Type" minOccurs="0"/>
 *         &lt;element name="ValidationAuthorityEntityID" type="{http://www.gleif.org/data/schema/leidata/2016}Tokenized500Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidationAuthorityType", propOrder = {
    "validationAuthorityID",
    "otherValidationAuthorityID",
    "validationAuthorityEntityID"
})
public class ValidationAuthorityType {

    @XmlElement(name = "ValidationAuthorityID", required = true)
    protected String validationAuthorityID;
    @XmlElement(name = "OtherValidationAuthorityID")
    protected String otherValidationAuthorityID;
    @XmlElement(name = "ValidationAuthorityEntityID")
    protected String validationAuthorityEntityID;

    /**
     * Gets the value of the validationAuthorityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationAuthorityID() {
        return validationAuthorityID;
    }

    /**
     * Sets the value of the validationAuthorityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationAuthorityID(String value) {
        this.validationAuthorityID = value;
    }

    /**
     * Gets the value of the otherValidationAuthorityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherValidationAuthorityID() {
        return otherValidationAuthorityID;
    }

    /**
     * Sets the value of the otherValidationAuthorityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherValidationAuthorityID(String value) {
        this.otherValidationAuthorityID = value;
    }

    /**
     * Gets the value of the validationAuthorityEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationAuthorityEntityID() {
        return validationAuthorityEntityID;
    }

    /**
     * Sets the value of the validationAuthorityEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationAuthorityEntityID(String value) {
        this.validationAuthorityEntityID = value;
    }

}
